[package]
name = "scheme"
version = "0.1.0"
edition = "2021"
authors = ["Overmind JIANG <p90eri@gmail.com>"]

[[bin]]
name = "scheme"
path = "src/driver.rs"

[lib]
name = "scheme"
path = "src/lib.rs"

[dependencies]
byteorder = "*"
bit-vec = "*"
env_logger = "*"
log = "*"
fnv = "*"

[dependencies.assembler]
path = "../assembler"
