[package]
name = "scheme"
version = "0.1.0"
authors = ["Overmind JIANG <p90eri@gmail.com>"]

[dependencies]
byteorder = "*"
env_logger = "*"
log = "*"
fnv = "*"

[dependencies.assembler]
path = "../assembler"
